services:
  app:
    build:
      context: .
    image: certplay
    ports:
      - "${PORT:-3000}:3000"
    environment:
      - NUXT_PUBLIC_SUPABASE_URL=${SUPABASE_URL}
      - NUXT_PUBLIC_SUPABASE_KEY=${SUPABASE_KEY}
      - NUXT_KINDE_CLIENT_ID=${KINDE_CLIENT_ID}
      - NUXT_KINDE_CLIENT_SECRET=${KINDE_CLIENT_SECRET}
      - NUXT_KINDE_AUTH_DOMAIN=${KINDE_AUTH_DOMAIN}
      - NUXT_KINDE_REDIRECT_URL=${KINDE_REDIRECT_URL}
      - NUXT_KINDE_LOGOUT_REDIRECT_URL=${KINDE_LOGOUT_REDIRECT_URL}
      - NUXT_KINDE_POST_LOGIN_REDIRECT_URL=${KINDE_POST_LOGIN_REDIRECT_URL}
      - NUXT_KINDE_PASSWORD=${KINDE_PASSWORD}