services:
  app:
    build:
      context: .
      dockerfile: .nixpacks/Dockerfile
    ports:
      - "${PORT:-3000}:3000"
    environment:
      - PORT=${PORT:-3000}
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_KEY=${SUPABASE_KEY}
      - NODE_ENV=${NODE_ENV:-development}